# -*- coding: utf-8 -*-
"""Dictionary.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u2V0XKivdDEhzvBk9d3bnmesD_cmivIF
"""

d = {'greg': 1, 'steve': 2, 'rob': 3}
print(d)

#add key:val in dictionary: O(1)

d['arsh'] = 4

#check for presence of key in dictionary: O(1)
if 'greg' not in d:
  print(True)

#Check value corresponding to a key in dictionary: O(1)
print(d['greg'])

#loop over key:val pairs #O(n)
for k,v in d.items():
  print(k,v)

#Defaultdict

from collections import defaultdict
d = defaultdict(list)

d[2]

# Counter
from collections import Counter
string = 'aaabbbccc'
c = Counter(string)
print(c)